import Head from "next/head";
import Avatar from "../components/Avatar";
import ViewGridIcon from "@heroicons/react/solid/ViewGridIcon";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png"
        />
      </Head>
      {/* Header */}
      <header className="flex w-full p-5 justify-between text-gray-700 text-sm">
        {/* left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />

          <Avatar
            url={`https://avatars.githubusercontent.com/u/61621763?v=4`}
          />
        </div>
      </header>
      {/* body */}
      {/* footer */}
    </div>
  );
}
