import Head from "next/head";
import Avatar from "../components/Avatar";
import ViewGridIcon from "@heroicons/react/solid/ViewGridIcon";
import Image from "next/image";
import SearchIcon from "@heroicons/react/outline/SearchIcon";
import MicrophoneIcon from "@heroicons/react/solid/MicrophoneIcon";
import Footer from "../components/Footer";
export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-suite-everything-you-need-know-about-google-newest-0.png"
        />
      </Head>
      {/* Header */}
      <header className="flex w-full p-5 justify-between text-gray-700 text-sm">
        {/* left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />

          <Avatar
            url={`https://avatars.githubusercontent.com/u/61621763?v=4`}
          />
        </div>
      </header>
      {/* body */}
      <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
        <Image
          src="http://assets.stickpng.com/images/580b57fcd9996e24bc43c51f.png"
          width={300}
          height={100}
          alt=""
        />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            className=" flex-grow focus:outline-none"
            type="text"
            name=""
            id=""
          />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button className="button">Google Search</button>
          <button className="button">{`I'm Feeling Lucky`}</button>
        </div>
      </form>
      {/* footer */}
      <Footer />
    </div>
  );
}
